# This is a basic workflow to help you get started with Actions

name: Python application

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup Python environment
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Run your Python script
      - name: Run Python script
        run: |
          python script_for_github_action.py
          git config user.email "stitching.coder@gmail.com"
          git config user.name "Laney"
          git add .
          git commit -m "Update from GitHub Action"
          git push
